
# The name of your website.
name: Fei Shen
shortname: Fei

description:

  # Description of your site. This will show up in google.
  meta: This is the website all about Fei Shen. Powered by Jekyll.

  # Description of your site. This will show up on the front page.
  #subtitle:

author:
  name: Fei Shen

  # Necessary for contact page
  email: philshenfei@gmail.com

  # Optional text (html) to display after author name. Leave empty if you don't
  # want it.
  info:

url:
baseurl:

# language attribute in <html> element.
lang: en

# FROM THIS POINT ON EVERYTHING IS OPTIONAL

##############
# APPEREANCE #
##############


footer-text: © 2017 Fei Shen. Published with <a href="https://pages.github.com/">GitHub Pages</a>, Powered by <a href="http://jekyllrb.com">Jekyll</a>.

# Preferably 64px in height. Leave empty = disable.
logo-image: 

# Color used throughout the theme. Format: R, G, B.
theme-color: 0, 240, 255 # Original: 0, 240, 255

# Text color used throughout the theme. Format: R, G, B.
text-color: 0, 0, 0 # Original: 0, 0, 0

# Background color used throughout the theme. Format: R, G, B.
# Note: if you change the background color AND you use cover images, you should
#       also change the CSS gradient in "_includes\gradient.css" to match the
#       background color. Edit and copy it from here:
#       http://www.colorzilla.com/gradient-editor/#ffffff+0,ffffff+100&0+0,1+100
background-color: 255, 255, 255 # Original: 255, 255, 255

display-author-post-page: true
display-author-front-page: true

# http://alanwsmith.com/jekyll-liquid-date-formatting-examples
date_format: "%b %-d, %Y"


# Display links for the previous and next post on post pages.
display-next-prev-post: true

# Leave empty if you don't want comments on post pages.
disqus-shortname: philshenfei  


#####################
# CUSTOMIZABLE TEXT #
#####################

# Useful for translating into other languages.

var_on_the_web: On the web
var_read: Read # Text after each post summary on the homepage.
var_newer: Newer
var_older: Older
var_next_post: Next post
var_previous_post: Previous post
var_less_than_a_minute_read: Less than a minute read
var_min_read: min read # Text after reading time. Example: 5 min read.
var_post_by: Post by
var_guest_post_by: Guest post by
var_your_email: Your email
var_your_message: Your message


##################
# BUILD SETTINGS #
##################

# You don't have to change these.
# highlighter: pygments or rouge
exclude: [vendor]
highlighter: rouge
kramdown:
  input: GFM
paginate_path: "/page-:num/"
permalink: pretty
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: "<!--more-->"